### ISSUE TITLE
lint: Create configuration file

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/website-niaefeup-backend-old#101]
Currently, we're using the default configuration of ktlint in Github's action and most of the team members are also using the ktlint plugin in IntelliJ. However, the default of the plugin is different from what is running in the actions.

We should have a consistent configuration in the repo that's used by the plugin and in the actions.

**Comment by bdmendes** [comment]
This is annoying me a bit, so I'll have a look at this. Maybe we do not need an explicit editor config but should simply enforce ktlint defaults on the GH action.
