### ISSUE TITLE
assets: investigate storage and link to activities

### ISSUE THREAD

**Issue by bdmendes** [NIAEFEUP/website-niaefeup-backend-old#11]
Since both projects, events, posts and members should be feeded with images, we should investigate how to store them, possibly in Cloudfare CDN, that we have an account for and use in the current website.

**Comment by BrunoRosendo** [comment]
Cloudinary might also be an option to consider

**Comment by BrunoRosendo** [comment]
We cant start by adding this functionality to projects and events (imagePath attribute)
