### ISSUE TITLE
posts: query a single post by a slug name

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/website-niaefeup-backend-old#25]
Currently, fetching a single post is done using its ID. This is also true for projects and events. Therefore, the page that will be used by the frontend user will be something like `ni.fe.up.pt/posts/134`.
Instead, we can think about using a slang name for a URL like `ni.fe.up.pt/posts/tts-new-release` which is more user friendly. We can also think about doing this for projects, events or other resources where it makes sense.

**Comment by limwa** [comment]
It should be noted that those properties should be marked unique in the model. How? I have no clue 😅

**Comment by BrunoRosendo** [comment]
@limwa Something from here should work fine 
https://www.baeldung.com/jpa-unique-constraints

`@UniqueConstraint` for validation or even `@Column(unique=true)` for the DB

**Comment by BrunoRosendo** [comment]
Adding to the issue, I think this is currently even more useful for activities (projects and events) than posts, even though it applies to all of them
