### ISSUE TITLE
global: add proper logging

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/website-niaefeup-backend-old#32]
Currently, the only logs we have are errors printed to `stderr`. We should have a better and consistent way of logging (e.g. error, info, debug, etc.). We can look at the available libraries and other Kotlin/Spring projects to choose.

**Comment by limwa** [comment]
Log4J :eyes: :laughing:

**Comment by ttoino** [comment]
Relevant spring boot docs https://docs.spring.io/spring-boot/docs/3.0.2/reference/htmlsingle/#howto.logging
