### ISSUE TITLE
events: gallery of photos

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/website-niaefeup-backend-old#43]
An event (and maybe a project too) should have a gallery displaying an arbitrary number of photos of the event after it occurred.

We should add the path of these photos to the model and create endpoints capable of storing and deleting those photos. We should also ensure the `GET project/{id}` endpoint includes this gallery.

**Comment by AvilaAndre** [comment]
If the gallery exists in both Event and Project, could I move this to the Activity? I'm going to implement it only on the Event for now.

**Comment by BrunoRosendo** [comment]
> If the gallery exists in both Event and Project, could I move this to the Activity? I'm going to implement it only on the Event for now.

I think the gallery will only exist for the events, but feel free to confirm in the team's channel
