### ISSUE TITLE
readability: use all-open compiler plugin for simplifying abstract entities

### ISSUE THREAD

**Issue by bdmendes** [NIAEFEUP/website-niaefeup-backend-old#99]
Instead of explicitly "opening" abstract entity fields like we are doing in the `Activity` model, we could instead rely on [this](https://kotlinlang.org/docs/all-open-plugin.html) to create a custom `AbstractEntity` that does this for us.

**Comment by BrunoRosendo** [comment]
Do Activity fields even need to be open? I don't think so, they're not being overridden since they're passed as params in Event and Project's constructors
